#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
export PATH=$SCRIPT_DIR/tools:$PATH

RTDIR=$(runtime_dir)
TMPDIR=$(mktemp_dir)

SOCKET_FILE=$RTDIR/server.sock

ACTUAL_FILE=$TMPDIR/actual.txt
DESIRED_FILE=$TMPDIR/desired.txt

"$SCRIPT_DIR/server" "pipe://$SOCKET_FILE" "$ACTUAL_FILE" &
SERVER_PID=$!
waitsock appear "$SOCKET_FILE"

function on_exit {
    termproc $SERVER_PID
    rm -f "$SOCKET_FILE" >/dev/null 2>&1
}
trap on_exit EXIT

sendrec pipe --socket "$SOCKET_FILE" 0
sendrec pipe --socket "$SOCKET_FILE" 3
sendrec pipe --socket "$SOCKET_FILE" 22
sendrec pipe --socket "$SOCKET_FILE" 0 3 22

termproc $SERVER_PID
waitsock disappear "$SOCKET_FILE"

cat >"$DESIRED_FILE" <<-EOM
[0]()
[3](Lor)
[22](Lorem ipsum dolor sit )
[0]()
[3](Lor)
[22](Lorem ipsum dolor sit )
EOM

diff "$DESIRED_FILE" "$ACTUAL_FILE"
