#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
export PATH=$SCRIPT_DIR/tools:$PATH

TMPDIR=$(mktemp_dir)

IP4=127.0.0.1
PORT=8777

ACTUAL_FILE=$TMPDIR/actual.txt
DESIRED_FILE=$TMPDIR/desired.txt

"$SCRIPT_DIR/echo_server" >"$ACTUAL_FILE" &
SERVER_PID=$!
waitport listen "$PORT"

function on_exit {
    termproc $SERVER_PID
}
trap on_exit EXIT

sendrec tcp --ip4 "$IP4" --port "$PORT" 3 21 4

termproc $SERVER_PID
waitport unlisten "$PORT"

cat >"$DESIRED_FILE" <<-EOM
Lor
Lorem ipsum dolor sit
Lore
EOM

diff "$DESIRED_FILE" "$ACTUAL_FILE"
