#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
export PATH=$SCRIPT_DIR/tools:$PATH

TMPDIR=$(mktemp_dir)

IP4=127.0.0.1
PORT=8765

RECV_MSGS_FILE=$TMPDIR/received.msgs
ACTUAL_FILE=$TMPDIR/actual.txt
DESIRED_FILE=$TMPDIR/desired.txt

echo "$TMPDIR"

cat >"$DESIRED_FILE" <<-EOM
[5] (Hello)
EOM

recvrec --ip4 "$IP4" --port "$PORT" >"$RECV_MSGS_FILE" &
RECVREC_PID=$!
waitport listen "$PORT"

"$SCRIPT_DIR/send_hello"
CLIENT_PID=$!
waitproc $CLIENT_PID 2

function on_exit {
    termproc $CLIENT_PID
    termproc $RECVREC_PID
}
trap on_exit EXIT

termproc $CLIENT_PID
waitport unlisten "$PORT"
termproc $RECVREC_PID

disrec "$RECV_MSGS_FILE" >"$ACTUAL_FILE"

diff "$DESIRED_FILE" "$ACTUAL_FILE"
