#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
export PATH=$SCRIPT_DIR/tools:$PATH

TMPDIR=$(mktemp_dir)

IP4=127.0.0.1
PORT=60722

INPUT_FILE=$TMPDIR/input.txt
ACTUAL_FILE=$TMPDIR/actual.txt
DESIRED_FILE=$TMPDIR/desired.txt

cat >"$INPUT_FILE" <<-EOM
First line
Second line
Third line
EOM

"$SCRIPT_DIR/client" "sc+tcp://$IP4:$PORT" "$INPUT_FILE" "$ACTUAL_FILE" &
SERVER_PID=$!
waitport listen "$PORT"

function on_exit {
    termproc $SERVER_PID
}
trap on_exit EXIT

sendrec tcp --ip4 "$IP4" --port "$PORT" 0
sendrec tcp --ip4 "$IP4" --port "$PORT" 3
sendrec tcp --ip4 "$IP4" --port "$PORT" 22
sendrec tcp --ip4 "$IP4" --port "$PORT" 0 3 22

termproc $SERVER_PID
waitport unlisten "$PORT"

cat >"$DESIRED_FILE" <<-EOM
parse_args
server_new
server_uv_init
server_init
async_init
signal_init
signal_init
idle_init
client_init
server_bind_and_listen
server_on_connection_success
client_on_accept_success
alloc_record
client_on_recv_success
[0]()
free_record
alloc_record
client_on_recv_eof
close_socket
free_record
client_on_close
server_on_connection_success
client_on_accept_success
alloc_record
client_on_recv_success
[3](Lor)
free_record
alloc_record
client_on_recv_eof
close_socket
free_record
client_on_close
server_on_connection_success
client_on_accept_success
alloc_record
client_on_recv_success
[22](Lorem ipsum dolor sit )
free_record
alloc_record
client_on_recv_eof
close_socket
free_record
client_on_close
server_on_connection_success
client_on_accept_success
alloc_record
client_on_recv_success
[0]()
free_record
alloc_record
client_on_recv_success
[3](Lor)
free_record
alloc_record
client_on_recv_success
[22](Lorem ipsum dolor sit )
free_record
alloc_record
client_on_recv_eof
close_socket
free_record
client_on_close
signal_cb
async_cb
close_socket
server_on_close
server_del
EOM

diff "$DESIRED_FILE" "$ACTUAL_FILE"
