#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

function fatal {
    echo >&2 "$1"
    exit 1
}

DIR=""
if test -d /run; then
    DIR=/run
elif test -d /var/run; then
    DIR=/var/run
fi

if ! test -z "$DIR"; then
    if touch "$DIR/touch_this_OPWMA" 2>/dev/null; then
        rm "$DIR/touch_this_OPWMA"
        echo -n "$DIR"
        exit 0
    fi
fi

DIR=$("$SCRIPT_DIR/mktemp_dir")
echo -n "$DIR"
