#!/bin/bash

function help {
    echo "Usage: temrproc <PID>"
    exit 1
}

function stall { sleep 0.05; }

function proc_exist {
    pid=$1
    kill -0 "$pid" 2>/dev/null && return 0
    return 1
}

function wait_proc_exit {
    pid=$1
    for _ in {0..9}; do
        if ! proc_exist; then
            return 0
        fi
        stall
    done
    return 1
}

function termproc {
    pid=$1
    proc_exist "$pid" && kill -2 "$pid" >/dev/null 2>&1 && wait_proc_exit "$pid"
    proc_exist "$pid" && kill -9 "$pid" >/dev/null 2>&1 && wait_proc_exit "$pid"
}

[ $# -ne 1 ] && help
termproc "$1"
